// Objective-C API for talking to server Go package.
//   gobind -lang=objc server
//
// File is generated by gobind. Do not edit.

#ifndef __Server_H__
#define __Server_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void ServerAddTrackers(NSString* _Nullable trackers);

FOUNDATION_EXPORT void ServerStart(NSString* _Nullable pathdb, NSString* _Nullable port, BOOL roSets, BOOL searchWA);

FOUNDATION_EXPORT void ServerStop(void);

FOUNDATION_EXPORT NSString* _Nonnull ServerWaitServer(void);

#endif
