
// Objective-C API for talking to the following Go packages
//
//	server
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TorrServer_FRAMEWORK_H__
#define __TorrServer_FRAMEWORK_H__

#include "Server.objc.h"
#include "Universe.objc.h"

#endif
