# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugin designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Core Lints
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_string_interpolations: true
#
#    # Architecture & Lifecycle Strictness
#    use_build_context_synchronously: true
#    discarded_futures: true
#    cancel_subscriptions: true
#    close_sinks: true
#    unawaited_futures: true
#    avoid_dynamic_calls: true
#
## Configure Riverpod Custom Lints
#custom_lint:
#  rules:
#    riverpod_avoid_global_provider: true
#    riverpod_avoid_read_inside_build: true
#    riverpod_avoid_watch_outside_build: true
#    riverpod_notifier_parameters: true
#    riverpod_async_notifier_error_handling: true
